[package]
name = "mib"
version = "0.1.0"
authors = ["mohaque"]

[dependencies]
build = { path = "../build" }
config = { path = "../config" }
plugin = { path = "../plugin" }

failure = "^0.1"
log = "^0.4"
serde_derive = "^1.0"
simple_logger = "0.5.0"
