[package]
name = "config"
version = "0.1.0"
authors = ["mohaque"]

[dependencies]
build = { path = "../build" }
failure = "^0.1"
log = "^0.4"
serde = "1.0"
serde_derive = "^1.0"
serde_yaml = "0.7"
simple_logger = "0.5.0"
yaml-rust = "0.4.0"